### PR TITLE
Review resources

### PR DESCRIPTION
**Pull request by uzername**
Walked through some links in resource file and added one nice link to tutorial. Did not remove anything

### CODE REVIEW

**Comment by daerogami** [comment]
I guess that means I need to finish my changes so this can get merged in. I'll work on them tomorrow evening (EST) and finish up what I was doing so these changes can get merged in as well.

**Comment by daerogami** [comment]
@uzername I'm gonna leave this PR open for a little longer. I went ahead and merged my updates with yours.
If you have time to explore some of those items with a "?" in the defunct column that would be a great help, otherwise I'll get around to it eventually.
Thanks for your efforts thus far!

**Comment by uzername** [comment]
GLPlusPlus C++ OpenGL headers by Fiddler does not relate to this repository.

**Comment by daerogami** [comment]
Yeah, go ahead and remove that one.

**Comment by daerogami** [comment]
@uzername When convenient, can you rebase and rename this branch?

**Comment by uzername** [comment]
What do you mean by "rebase"? I have edited this on Github site directly.

**Comment by Nihlus** [comment]
@uzername You'll need to use a git client to do that. Clone the repo locally and work on that copy instead.

**Comment by daerogami** [comment]
@uzername If you need help, we can hop on discord and I'll walk you through it. Just let me know your timezone and what time you will be available.

**Comment by uzername** [comment]
Renaming branch is too dangerous. But "rebase" operation may work. Used this article: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by daerogami** [comment]
Thank you for you time and contribution!

**Pull request merged**
